apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment
spec:
  selector:
    matchLabels:
      app: order-db
  replicas: 1
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root # root password for MySQL
        - name: MYSQL_DATABASE
          value: orderdb # the name of the database
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: order-db-service
spec:
  selector:
    app: order-db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
